name: memee
description: Online meat & grocery app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.11.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  get_it: ^7.2.0
  go_router: ^6.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  pin_code_fields: ^8.0.1
  geolocator: ^10.1.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
