// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_dOrY_L09IggdUlrKedJUvosBI9gI73g',
    appId: '1:458698728419:web:6460d437462ac7f6a536d6',
    messagingSenderId: '458698728419',
    projectId: 'my-masjid-4cb75',
    authDomain: 'my-masjid-4cb75.firebaseapp.com',
    storageBucket: 'my-masjid-4cb75.appspot.com',
    measurementId: 'G-E8F8BLNES2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAohRvBsJznGlbDh-TH6hnhHnyV1sa-wNc',
    appId: '1:458698728419:android:2c5f26054d1b9c57a536d6',
    messagingSenderId: '458698728419',
    projectId: 'my-masjid-4cb75',
    storageBucket: 'my-masjid-4cb75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAis524M4RswnaKgOQsIDMrK9kavJD6uJU',
    appId: '1:458698728419:ios:02bb498348c00271a536d6',
    messagingSenderId: '458698728419',
    projectId: 'my-masjid-4cb75',
    storageBucket: 'my-masjid-4cb75.appspot.com',
    iosClientId: '458698728419-nl99hm11chftubupo6gg16odircum66o.apps.googleusercontent.com',
    iosBundleId: 'com.example.masjidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAis524M4RswnaKgOQsIDMrK9kavJD6uJU',
    appId: '1:458698728419:ios:e7a3e516cdd74449a536d6',
    messagingSenderId: '458698728419',
    projectId: 'my-masjid-4cb75',
    storageBucket: 'my-masjid-4cb75.appspot.com',
    iosClientId: '458698728419-p98jvdjbn1ieg6a17k7epj1loatcmf25.apps.googleusercontent.com',
    iosBundleId: 'com.example.masjidApp.RunnerTests',
  );
}
